---
name: 'Build and deploy 🚀'

on:
  push:

permissions:
  id-token: write # for OIDC

env:
  TF_LOG: ERROR
  TF_INPUT: false

jobs:
  build:
    name: Build Lambda
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: List files after checkout
        run: tree

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4

      - name: Bun install
        run: bun ci

      - name: Bun audit
        run: bun audit

      - name: Run TypeScript type check
        run: bun run typecheck

      - name: Build
        run: bun run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-bundle
          path: lambda/dist

  terraform-check:
    name: Run tflint, tfsec, terraform validate
    needs: build
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: List files after checkout
        run: tree

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4

      - name: Terraform validate
        run: terraform validate

      - name: Terraform format check
        run: terraform fmt -check

      - name: tflint
        run: tflint

      - name: tfsec
        run: tfsec --minimum-severity=HIGH

  terraform-plan-apply:
    name: Run terraform plan/apply
    needs: terraform-check
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Restore build artifacts
        uses: actions/download-artifact@v5
        with:
          name: lambda-bundle
          path: lambda/dist

      - name: List files after checkout
        run: tree

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check caller identity
        run: aws sts get-caller-identity

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform --non-interactive apply
